Update docs.centra.com graphql information
centrahq/api-documentation pull request #164
Opened 2021-03-11 08:56 UTC by VollTheGreat

### Task
[CCT-2288](https://centracommerce.atlassian.net/browse/CCT-2288)

### TODO
Pages about:

- [x] What GraphQL is
- [x] How it is different from other APIs, 
- [x] How to get authorized
- [ ] Information about connections/pagination
- [ ] Query examples 
- [ ] Links to changelog and auto-docs.

Additionally:
- [ ] Tell Support department about the new docs and ask them for a review.

2021-03-18 07:55 UTC, sirtopp requested changes
I would organize the sections in authorization like this:

```
# General Information
## Access token
 - what it is (set of permissions)
 - how it relates to user
 - expires
 - can be revoked (?)

### Token revocation (currently missing in docs)

## Authorizing requests

### Header
### Cookie

## Obtaining access token

### AMS
#### (special case) get/generate admin toekn
### Mutation
```

AND add a section about `## Base url ` to the overview file.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +In [Altair GraphQL](https://altair.sirmuel.design/) you click on a sun rays (?) icon on the left and set header name to Authorization, and content to Bearer `{{graphql_token}}`. `{{graphql_token}}` i
I would provide a generic information about header to send, maybe an example with code block, like this:

```
POST {base url}/graphql

Authorization: Bearer {access token}
```

(either with placeholders as above or exemplary values}

Only then an example with specific GraphQL Client like Altair. Not everyone must be using this client and providign a generic information will make this doc tool-agnostic.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +## General information
A paragraph about what access token represents and what are it's properties would most likely be very welcome:

 - access token is bound to a set of permissions
 - it has a mandatory expiration time (min/max values?)
 - can be revoked (it can, right?)

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +In [Altair GraphQL](https://altair.sirmuel.design/) you click on a sun rays (?) icon on the left and set header name to Authorization, and content to Bearer `{{graphql_token}}`. `{{graphql_token}}` i
Or... Many documentations treat `curl` as generic API client and provide examples of command line curl commands. It's a "de facto standard" for API clients.
So in this example something like:

```
$ curl "${base_url}/graphql" \
     -H "Authorization: Bearer ${graphql_token}"
.... and so on
```

(in that case just make sure that the example provided actually works)

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +//TBD IMAGE
Yeah.. the image :)

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +- using graphql and AMS admin token
If there is an explanation what a `admin token` is then please link to it. If there is none, then short explanation would be most welcome

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +- using graphql and AMS admin token
Ok, nevermind. There is a description below.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +and  get(generate) Admin token //screenshot
Just reminding about screenshot

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +Add cookie named `graphql-access` with only the access token as value.
As above: an example would be nice, either `curl` or pseudo-cdoe of the request:

```
POST {base url}/graphql

Cookie: graphql-access={graphql token}
```

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +For using Centra graphql you need user token with correct permissions. This could be done in two ways:
I think you are missing a header here.

Above 2 sections were about how to pass the token:

```
 -- add a haeder
 -- add a cookie
```

And now the description is about how/where to get the token from.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +
This should go to a separate section, probably at the very top of the document. I will post a proposition about sections in the review summary

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +`Authorization: Bearer {{admin_token}}`
See, you actually provided a generic example that I was referring to above. If you put it above then it will not be useful here. Just adding `use the token obtained from AMS [#link to section]` would be enough.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +```
You could post a simpler query without vars. They are not required for the mutation to work. It would simplify the example.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +## General information
P.S. Since we are using a term `user` below we should also explain how tokens relate to users.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +GraphQL is used to Send a query to Centra API and get exactly what you need, nothing more and nothing less. GraphQL queries always return predictable results. Apps using GraphQL are fast and stable b
Nice explanation :) I would add a "read more" link to official docs: https://graphql.org/

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +GraphQL is the new trend and best alternative to Rest-based architecture that pulls all relevant data from multiple sites with a single request. It improves client-server interactions and reduces the
1. I believe that REST is capitalized
2. I'm always careful with statements with `best` or `worst`. In 95% of the cases it really depends on the case what is best for the user.

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +Correct permissions
What are the correct permissions?

2021-03-18 07:55 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +Authentication token
Do you mean the "admin token" from sections above? If so then this is not required, as you provided the steps to create one if you don't have it.

2021-03-25 13:01 UTC, hstrychalski requested changes
Small suggestions, but in general - very concise and clear description! 🚀

2021-03-26 07:47 UTC, sirtopp commented on source/reference/beta/backend-api/authorization.md
> +## Obtaining Access Token
That is an excellent idea.. 🤔

2021-03-26 07:58 UTC, piotr-symonowicz commented on source/reference/beta/backend-api/overview.md
> +.. api-name:: Backend API
Is that how we call it? I thought it would be "Integration API"

2021-03-26 07:59 UTC, piotr-symonowicz commented on source/reference/beta/backend-api/overview.md
> +```note:: The Backend GraphQL is not yet released. Please stay tuned.
I'd rather we say it's in beta and read-only, people are already using it so it's weird to say it's "not yet released"

2021-03-26 08:28 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +.. api-name:: Backend API
Actually I don't know how we are supposed to name it publicly. I'm gonna name it `Integration API` since you know it better :)

2021-03-26 08:28 UTC, sirtopp commented on source/reference/beta/backend-api/overview.md
> +```note:: The Backend GraphQL is not yet released. Please stay tuned.
I'ts not read only anymore (there are first mutations released) but it sure is in beta.

2021-03-26 08:54 UTC, hstrychalski approved these changes

2021-03-29 06:54 UTC, merged