Paypal Commerce plugin documentation
centrahq/api-documentation pull request #167
Opened 2021-03-26 10:03 UTC by zzzarka

2021-03-31 11:49 UTC, sirtopp requested changes
Tiny feedback. Docs are understandable for an average dev to start using it. Small editorial issues.

2021-03-31 11:52 UTC, zzzarka commented on source/guides/plugins/paypal-commerce.md
> +   :scale: 30 %
no idea :D i copied this from Stripe docs :) but i agree it is tiny so i will scale it up.

2021-03-31 11:57 UTC, zzzarka commented on source/guides/plugins/paypal-commerce.md
> +```
:D this was copied from stripe .. or maybe adyen documentation .. i will see if that has something to say about it :)

2021-04-01 08:10 UTC, sirtopp commented on source/guides/plugins/paypal-commerce.md
> +## Redirect
Yup, makes sense. :)

2021-04-01 08:12 UTC, sirtopp commented on source/guides/plugins/paypal-commerce.md
> +```
Ok, so it stays that way then. :)

2021-04-01 08:17 UTC, sirtopp approved these changes

2021-09-01 13:48 UTC, closed without merging