DTCT-607: Integration Best Practices Docs
centrahq/api-documentation pull request #442
Opened 2023-02-01 11:11 UTC by adamaru

[DTCT-607: Integration Best Practices Docs](https://centracommerce.atlassian.net/browse/DTCT-607)

Added best practices description as separate page along with links to it.

2023-02-08 09:13 UTC, sirtopp requested changes

2023-02-08 09:13 UTC, sirtopp commented on pages/03.fe-development/13.best-practices/docs.md
> +It allows the client to retrieve only the data it needs and to process the data in a way that is most efficient for their use case.
Please emphasize that
 - pagination is prerequisite in product listing, otherwise the responses might miss products or return errors.
And add an example of paginated request to `POST /products` with limit/offset.

2023-02-08 09:13 UTC, sirtopp commented on pages/03.fe-development/13.best-practices/docs.md
> +Therefore, we recommend that **responses should be limited to a few kilobytes in size**
I'm thinking now if we are able to serve the response under few kilbytes now 🤔 . Might not be doable.. :D Maybe remove that sentence about KBytes after all.

2023-02-10 09:54 UTC, hstrychalski commented on pages/03.fe-development/13.best-practices/docs.md
> +Therefore, we recommend that **responses should be limited to a few kilobytes in size**
How is that a best practice for the partners? We're the party that is responsible for response size.
I think that pagination is the mechanism to limit the response size and it's mentioned in paragraph before.

about KBytes - POST /products response have up to 70MB :D 
I think you can fetch max 10 products if you want to go below 1MB

2023-02-10 14:11 UTC, sirtopp approved these changes
Solid first version 👍🏼

2023-02-23 10:35 UTC, merged